# Generated by Django 2.2 on 2019-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('token', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=500, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user_token',
                'verbose_name_plural': 'user_token',
                'db_table': 'user_token',
            },
        ),
    ]
